### ISSUE TITLE
Import/Export in the API and the UI

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#10]
Is necessary to implement an import/export endpoint and functionality in the UI to let developers gain speed in the process of managing their agents.

**Comment by dcalvom** [comment]
We haven't solved the UI part of this one...

**Comment by dcalvom** [comment]
@broham89 this is not urgent but I remember @wrathagom said something about adding an import option in the create page of the agent. If so how you envision that?

**Comment by broham89** [comment]
<img width="1047" alt="import" src="https://user-images.githubusercontent.com/11262149/41069032-c2452370-69b1-11e8-821a-2e506608e46f.png">

**Comment by wrathagom** [comment]
I think so of the conversation needs to go on where to put this in the UI. Does the user click on the create agent button and get taken to the screen with the form, but there input button is someplace? Or does clicking on the Create agent button take them to a landing page where they have to choose: New Agent, Import Agent, Demo agent.

If we know for sure we're going to do the pre-build demo agents at some point we could use this opportunity to lay the groundwork.

**Comment by broham89** [comment]
If the import agent was on the screen that has: New Agent, Import Agent, & Demo agent - and the user imported an agent. Would they still need to input the name of the agent description and other present inputs for creating an agent? Because I'm thinking if they import an agent it should automatically fill out the necessary input values name, description, threshold value, etc... But if User needs to input name, description, threshold value, after importing then it would be best to just have them import it into the `create agent page `located possibly on the top. 

Idk if i'm going in a far direction with this...

**Comment by broham89** [comment]
<img width="1243" alt="static" src="https://user-images.githubusercontent.com/11262149/41130071-a8e954ae-6a7a-11e8-9fd8-25a18aee1b75.png">
<img width="1244" alt="after" src="https://user-images.githubusercontent.com/11262149/41130074-ac6d0332-6a7a-11e8-9632-51e825acde33.png">

^ this would be in the create agent page holding the import button.

**Comment by broham89** [comment]
<img width="1244" alt="artboard 31" src="https://user-images.githubusercontent.com/11262149/41130329-cc5a8af6-6a7b-11e8-804c-82ef5117e9cf.png">

^export button would be in the header

**Comment by wrathagom** [comment]
@broham89 we need to think about how this would work in the new UI. ideally the front agent selection page would have a + button for create and an import button as well?

And then someplace in the agent tab we could place an export button?

**Comment by wrathagom** [comment]
I like the import button on the create page.

Still not sold on the export options. I'd rather leave the main page agent cards clear since we just remove the three dots... and if you place them on the right side of the buttons in the agent page then those buttons are in a different place then other screens.

Maybe export is on bottom left of agent screen opposite delete? Or maybe it's at the bottom of the each agent card on the main page, mirroring the import button...

**Comment by broham89** [comment]
![agent list page hover export](https://user-images.githubusercontent.com/11262149/51875046-f7871580-2328-11e9-97d7-c59c884a17b5.png)
![v 2 - agent create screen](https://user-images.githubusercontent.com/11262149/51875062-0f5e9980-2329-11e9-82f4-7033a74e0016.png)

**Comment by wrathagom** [comment]
Do you have a preference or are either bad for UX reasons? Seems like the 2nd image makes it a little hidden.

I think the icons are reversed or not? when I think of exporting I think of downloading (down arrow) and import as uploading (up arrow).

**Comment by broham89** [comment]
For the first image, I thought to have the export in a different place from `import` top right would help differentiate the two at first glance. 2nd image, I wouldn't think it wouldn't be too hidden if the page doesn't expand. My other suggestion is having a tucked away in a `three-dot` icon... but i know we're trying to get away from that. And another would be have it placed in the row of subtabs on the far right. 

On a different note, i just thought of something cool if you can ask articulate in the chat panel `Where can i export an agent` and it will explain when and a url link directing to that page.

**Comment by wrathagom** [comment]
okay @broham89 @dcalvom let's go with the second image above. With the export icon in the bottom left hand corner of agent screen.
