### ISSUE TITLE
Let user mark system entities in the UI

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#128]
You can use system entities in the intent response. For example:

This is the current time in New York: {{slots.sys.duckling_time.from}}

Nonetheless, the user is not seeing those slots in the slots table. It should be nice to let users highlight system entities in the examples and even rename those to keep a better control of the slots.

**Comment by wrathagom** [comment]
@dcalvom this one is kind of related to #19 right? We were going to auto-highlight system entities.

There's actually several pieces to this, because if we auto-highlight we'll need a way for them to be able to un-highlight it. Or if we don't auto-highlight we'll need the ability to verify that what they have highlighted is actually a system entity.

Maybe what we should do is: When the user highlights a word we  see if his highlight range matches the range of any system entities. If it does we add those system entity options to the list. I don't know if the request to spacy and duckling can be done fast enough so that the user isn't bothered by the delay in showing the pop-up?

**Comment by wrathagom** [comment]
@dcalvom I think this one is done right?

**Comment by dcalvom** [comment]
At UI level it's done. We need to store the sys entities in the intent data as entities, but we need to make a small change in the API to ignore sys entities during training at the training data creation step.

**Comment by dcalvom** [comment]
Closed by 
https://github.com/samtecspg/articulate/commit/4209fa2f539203c9de457cd42984aef43c18914fC
