### ISSUE TITLE
deploy to facebook?

### ISSUE THREAD

**Issue by vilav** [samtecspg/articulate#149]
is there a way tp push the bot to Facebook Messenger with articulate?

**Comment by wrathagom** [comment]
Hey @vilav none of us personally have experience with Facebook Messenger Bots, though my current understanding was that [no one could create one right now](https://medium.com/landbot-io/can-we-trust-facebook-for-our-future-chatbot-strategy-fe7aa92c86a3).

Though [it sounds like they use simple web hooks](https://medium.com/crowdbotics/how-to-create-your-very-own-facebook-messenger-bot-with-dialogflow-and-node-js-in-just-one-day-f5f2f5792be5). Which can be used with Articulate.Depending on what their webhook payload looks like you may be able to point it directly to `agent/{id}/converse` otherwise you may need a small middle ware to translate what it sends into the format Articulate expect which is:

```
{
  "sessionId": "string",
  "text": "string",
  "timezone": "string"
}
```

We have started development on an API layer that would allow us to connect to multiple front end services. But don't have a date at this time when it will be integrated into Articulate. Let us know if we can help further!

**Comment by tanmay3108** [comment]
Any update on this..Articulate UI has a connection for this..can we do it?

**Comment by tanmay3108** [comment]
FB page keep saying "The URL couldn't be validated. Please try again."

**Comment by wrathagom** [comment]
We’ll test this here in a moment, but it was working very recently. Did you find the documentation for setting it up and do you have Articulate deployed on a public VM rather than local install?

**Comment by wrathagom** [comment]
Please create a new issue if you continue to have connection problems.
