### ISSUE TITLE
Slots lifespan

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#154]
If you have a slot that can be shared between intents that means that for the user whenever he executes the second intent the slot that he already filled it's going to be there.

We need to add something like a lifespan attribute to let a slot persist between frames (unit of a context).

**Comment by wrathagom** [comment]
@dcalvom if I remember correctly the issue was that the lifespans weren't applied consistently. If you were inside the domain then they lasted forever, but if you went outside the domain then the lifespans applied. The goal should be to make it consistent.

Also does it make the most sense to make these lifespans where they limit the forward life or history limits where they limit how far back inhibitory the agent can look to fill them? Something worth thinking about.

**Comment by wrathagom** [comment]
Okay, so, currently our context looks like this:

```
{
  "id": "1",
  "sessionId": "articulateUI",
  "actionQueue": [],
  "responseQueue": [],
  "creationDate": "1548380320000",
  "modificationDate": "1548391185000",
  "frames": [
    {
      "id": "28",
      "action": "Greet",
      "slots": {},
      "creationDate": "1548390908000",
      "modificationDate": "1548391185000"
    },
    {
      "id": "29",
      "action": "Order Pizza",
      "slots": {
        "Toppings": {
          "keyword": "Toppings",
          "value": [
            "ham"
          ],
          "original": [
            "ham"
          ]
        }
      },
      "creationDate": "1548390914000",
      "modificationDate": "1548391185000"
    }
  ]
}
```

I am proposing that we add a `savedSlots` key to the context object that looks like this:

```
{
   "id":"1",
   "sessionId":"articulateUI",
   "actionQueue":[],
   "responseQueue":[],
   "savedSlots":[
      "Toppings":{
         "remainingLife": 3,
         "keyword":"Toppings",
         "value":[
            "ham"
         ],
         "original":[
            "ham"
         ]
      }
   ]   "creationDate":"1548380320000",
   "modificationDate":"1548391185000",
   "frames":[
     ...
```

This allows us to check this key for saved slots when processing new requests.

- This is something we only check on new requests. Maybe when we create a frame?
- Rather than lifespan, I am thinking we should call this carryover or rollover?
- We should discuss what to call this "save slot value", "carry slot value", lifespan, carryover, rollover, etc
- The UI seems pretty simply, but still needs some discussion. Do we rely on check marks to turn it on, or special numerical values like -1 persists forever, 0 doesn't persist, etc.

**Comment by dcalvom** [comment]
Is this one still on testing phase? Can we close it?

**Comment by wrathagom** [comment]
It certainly needs more testing on my part, but I am good with closing for now.
