### ISSUE TITLE
API Specific README is out of date

### ISSUE THREAD

**Issue by marcoaleixo** [samtecspg/articulate#167]
Just a detail, this page is out of date: https://github.com/samtecspg/articulate/tree/master/api

**Comment by wrathagom** [comment]
@dcalvom we should simplify this page to where it's just how to run/dev mode the API. Not a super high priority, but we certainly need to keep it up to date. Or we could remove this and create an API section on our actual docs page... @milutz any input?

**Comment by dcalvom** [comment]
Well, this issue started because a user was trying to run the API locally. The thing is that the API in the past was in their own repo and used ES for data storage. So, I think the main goal of this issue is to modify the `Readme.md` file inside the API folder to let users run the API locally, and let them know a little bit of architecture.

**Comment by wrathagom** [comment]
Old API. new API readme looks good.
