### ISSUE TITLE
Rasa Core Integration

### ISSUE THREAD

**Issue by karthikbalu** [samtecspg/articulate#183]
### Feature Request
Articulate seem to solve only half of the problem with Rasa NLU but why Rasa Core is neglected?

Without Rasa Core how can we build a conversational chat bot with just the NLU?

Please shed some light, i'm seeing many similar projects on github and everyone seem to avoid integrating Rasa Core

Is there a way to integrate this project with Rasa Core, without this Articulate may be of no use, pls correct me if im wrong

Thanks

**Comment by wrathagom** [comment]
@karthikbalu we implement our own dialogue system instead of using Rasa Core. For three primary reasons:

- When we first started this project Core was not available
- Core is tough to boil down into a single API.
- Core can require a significant amount of training to learn basic dialogue.

All that said Core enables far more complex dialogue than Articulate will, but you have to be willing to spend the effort.

Our approach is similar to Dialogue Flow's where dialogue is managed with context and slot filling. Our long-term goal is that this "mechanical" approach can be used to bootstrap an ML-based approach with the mechanical dialogue slowly giving control to the intelligent one. Articulate is all about improving ease of use. We feel that in this way we can keep ease of use high while training something like Core in the background.

If you haven't done so yet it would be great if you could try to implement your dialogue in Articulate and let us know where it falls short.

**Comment by wrathagom** [comment]
@karthikbalu or @beevelop have either of you tried our Dialog yet?

**Comment by wrathagom** [comment]
Let us know if you all have a review of how we handle Dialogue. Closing until then.
