### ISSUE TITLE
Slot filling Response Prompts with high confidence in wrong intent

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#193]
If RASA recognized an intent but the scenario is not fulfilled with all the required slots, a text prompt will be sent to the user.

If this required slot is present in more than one intent, and the user trained the model in a way that the entered text to fill the slot will be recognized by more than one intent then it could happen that the conversation will deviate to another intent instead of the one that was on the process of fulfillment.

That's why we need to handle this in order to see if there is something we can do to keep the context with the same intent and fulfill the intent that caused the prompt instead of the deviating to another intent.

**Comment by wrathagom** [comment]
Part of me says that this goes back to needing a way to label certain training examples as an entity only. To keep the intent confidence low. So take the below example, the top several options are just there for recognizing the entities in response to the prompts.

<img width="1648" alt="2018-05-09_09-38-16" src="https://user-images.githubusercontent.com/1779894/39801824-b8e6e382-536c-11e8-80a3-65d34af1f539.png">

Perhaps rather than those being in the User Says section they belong in a section dedicated to prompt responses?

@ewoo @broham89 any thoughts on usability/common patterns.

From a technical perspective since we are using a CRF that is looking at sentence structure to extract the entities, it is important for us to have these alternative forms of usage. Additionally, my instinct tells me that eventually when we get many single word entity responses we will have large collision problems.

**Comment by wrathagom** [comment]
Will be addressed by #223
