### ISSUE TITLE
Getting time from duckling webhook

### ISSUE THREAD

**Issue by Johnz86** [samtecspg/articulate#204]
One of the most [common questions](https://blogs.msdn.microsoft.com/benjaminperkins/2016/11/21/most-common-chatbot-questions-and-how-to-answer-them/) towards chatbots is "What is the time?".
Is there a possibility to create a webhook towards the duckling and parse the response?
Currently there is duckling container available.  The problem is you can only define json/xml payload.
Duckling requires 'text=now' to get the current date. Response is json object with escaped value, which I have trouble to display via handlebars.
```json
[
  {
    "dim": "time",
    "body": "now",
    "value": "{\"values\":[{\"value\":\"2018-05-14T00:46:16.141-07:00\",\"grain\":\"second\",\"type\":\"value\"}],\"value\":\"2018-05-14T00:46:16.141-07:00\",\"grain\":\"second\",\"type\":\"value\"}",
    "start": 0,
    "end": 3
  }
]
```
Is it possible to use the duckling to display current time with webhook? Or is there any other way to display it with handlebars/entities?

**Comment by wrathagom** [comment]
Hey @Johnz86 what version are you running, we've made some handlebar additions in the latest versions so I don't want to suggest something that isn't available in your version. in 0.7.1 we added a bunch of [Handlebar helpers](https://github.com/helpers/handlebars-helpers).

I think you have at least a couple of options:
- Use [JSONparse](https://github.com/helpers/handlebars-helpers#jsonparse) to parse the stringified duckling value
- Use the [moment](https://github.com/helpers/handlebars-helpers#jsonparse) helper

I've not tried the moment helper so I don't know if you can specify a timezone or anything with it. Hopefully at a minimum the JSONparse works for you, something like:

```
Today is {{dateTimeFormat (get values.0.value (JSONparse this.0.value)) 'YYYY-MM-DD'}}
```

But again that is untested. The inntermost subexpression parses the JSON, then we get the value from it, then we format it.

**Comment by Johnz86** [comment]
@wrathagom Thank you for your response. Based on your reply I made a terrible mistake, I pulled the latest images available in docker hub and my entire stack stopped working :(

Setups is done in aws linux vm.
```
NAME="Amazon Linux"
VERSION="2 (2017.12)"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2 (2017.12) LTS Release Candidate"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (2017.12) LTS Release Candidate
```
Steps that I did in articulate folder: 
```
docker-compose pull
docker-compose up
```
This downloaded latest images 

Tag Name | Compressed Size | Last Updated
--- | --- | --- 
repo-head | 809 MB |  2 days ago


After the start of the ui, I did create a new bot. After creation of the bot, all will fail on creation of intents. I get following errors in ui web page browser console:
```
window.controllers/Controllers is deprecated. Do not use it for UA detection.
reactBoilerplateDeps.dll.js%20line%20720%20%3E%20eval:1362
Warning: Failed prop type: Invalid prop `agentDomains` supplied to `IntentListPage`.
    in IntentListPage (created by Connect(IntentListPage))
    in Connect(IntentListPage) (created by RouterContext)
    in main (created by App)
    in div (created by App)
    in App (created by AppWithProgressBar)
    in div (created by AppWithProgressBar)
    in AppWithProgressBar (created by Connect(AppWithProgressBar))
    in Connect(AppWithProgressBar) (created by RouterContext)
    in RouterContext (created by Router)
    in ScrollBehaviorContext (created by Router)
    in Router
    in IntlProvider (created by LanguageProvider)
    in LanguageProvider (created by Connect(LanguageProvider))
    in Connect(LanguageProvider)
    in Provider
warning.js:36:9
```
```
Unhandled promise rejection 
TypeError: agentDomains.domains is undefined
Stack trace:
render@http://34.244.49.207:3000/14.chunk.js line 190 > eval:241:13
_renderValidatedComponentWithoutOwnerOrContext/renderedElement<@webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:796:16
measureLifeCyclePerf@webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:75:12
_renderValidatedComponentWithoutOwnerOrContext@webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:795:25
_renderValidatedComponent@webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:822:27
performInitialMount@webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:362:25
mountComponent@webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:258:16
mountComponent@webpack:///./~/react-dom/lib/ReactReconciler.js?:46:18
performInitialMount@webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:371:18
mountComponent@webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:258:16
```
```
Unhandled promise rejection 
TypeError
​
columnNumber: 5
​
fileName: "http://34.244.49.207:3000/reactBoilerplateDeps.dll.js line 10768 > eval"
​
lineNumber: 63
​
message: "internalInstance is null"
​
stack: "getHostNode@webpack:///./~/react-dom/lib/ReactReconciler.js?:63:5\ngetHostNode@webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:384:12\ngetHostNode@webpack:///./~/react-dom/lib/ReactReconciler.js?:63:12
```
What is the last working version of articulate?

**Comment by Johnz86** [comment]
@wrathagom I rolled back to version 0.8.0 that works. Now with your proposed solution the problem is, that I am unable to specify the webhook type. If I pick json or fill text I will allways get an error:
```
{"statusCode":400,"error":"Bad Request","message":"\"webhookPayloadType\" is not allowed","validation":{"source":"payload","keys":["webhookPayloadType"]}}
```

**Comment by Johnz86** [comment]
![2018-05-14 17_37_49-create intent](https://user-images.githubusercontent.com/2708520/40007656-ac274eae-579d-11e8-9365-6f77353e4181.png)

**Comment by wrathagom** [comment]
So multiple responses here: on 0.8.0 I don't have any problem specifying a webhook and the webook does work for me. In the image you have posted above, for me, returns `quack!`. If your webhook still isn't working then there is a good chance something that Docker didn't get brought down/up'd as you expected. When going back and forth between versions we've seen problems with the correct container's not getting pulled/etc as expected.

I finally made it back to my computer and gave your original request a try. I now understand what you were meaning in your original request, Duckling expects a Content-Type similar to `application/x-www-form-urlencoded` but the only options we offer are `application/json` and `application/xml`.

So to get you what you need we need to do one or more of the below three things:

1. Modify Duckling to accept JSON/XML/query string parameters
2. Add a form encoding option.
3. Add in the `{{moment}}` helper, which doesn't seem to be installed.

**Comment by dcalvom** [comment]
Hi @Johnz86 we just pushed a fix on our master repo. So, now if you want to use duckling as a webhook for you intent response you can do the following:

Define your intent and enable the webhook for this intent:

![image](https://user-images.githubusercontent.com/7228045/40018037-57f838e0-5778-11e8-8592-1bd930882938.png)

In the webhook definition, set POST to the verb, enter your duckling url, in my case `http://localhost:8000/parse` and then select the new body type we added `URL Encoded`. Then in the payload editor, enter the data you want to send to duckling, in this case I sent the language and the text I want to parse to retrieve the current datetime:

![image](https://user-images.githubusercontent.com/7228045/40018119-97eb0e3c-5778-11e8-9113-045a36d642e6.png)

Finally define your agent response and extract the value from the webhook response using handlebars as follow:

![image](https://user-images.githubusercontent.com/7228045/40018152-b02d5fd6-5778-11e8-897a-bee22b05169e.png)

We use `webhookResponse.0.value.value` notation because duckling's response is an array of objects, so in order to get the first response, which is the current time you use the `.0.` key.

Finally you can test it in th conversation bar:

![image](https://user-images.githubusercontent.com/7228045/40018223-e17e7d40-5778-11e8-9ea6-620dc98f13f9.png)

Given this, I'm going to mark this issue closed by https://github.com/samtecspg/articulate/commit/8eeb0153427c379a1875f6247525ff75309e565c

**Docker cloud takes a while to building the new images of the containers**, so if you just read this comment just after I enter it wait for a little bit (30 mins) to let Docker cloud finish the creation of the images.

Regarding @wrathagom comment:
> If your webhook still isn't working then there is a good chance something that Docker didn't get brought down/up'd as you expected. When going back and forth between versions we've seen problems with the correct container's not getting pulled/etc as expected.

Please try to clean your docker and pull everything again, as we did a fresh start and everything seems to be fine.

**Comment by wrathagom** [comment]
Eh, Joh was running everything locally, not in Docker at all. For your use case, you need to reference Duckling via it's service name since it's running in a container and not on localhost.

keep in mind localhost when running in Docker is inside the API container, not your machine.

Try a url of `http://duckling:8000/prase`
