### ISSUE TITLE
Create a custom Dockerfile for new language

### ISSUE THREAD

**Issue by kurodenjiro** [samtecspg/articulate#277]
how can i update new language train model spacy after installed spacy or how can i update new langugage by docker

**Comment by wrathagom** [comment]
@kurodenjiro are you asking how to modify the Dockerfile to install a custom language?

**Comment by kurodenjiro** [comment]
yes

**Comment by kurodenjiro** [comment]
i writed spacy our country language  , can you add it on docker file for me on spg ?

**Comment by wrathagom** [comment]
Which language? We can certainly work something out.

**Comment by kurodenjiro** [comment]
vietnamese

**Comment by kurodenjiro** [comment]
@wrathagom  it's great

**Comment by milutz** [comment]
@wrathagom I think blog post is going to be the way to start.

Assuming the process to add is making a (file? directory?) visible in the Rasa container and adding (a line to the rasa config?) with the path to the model, we'll have an altered host file set anyway.

It’s just tiny changes in the process if you want to build it into the container instead of having it be an include directory.

If you can show me how to enable it, I can work on writing the instructions
