### ISSUE TITLE
Webhook not working for body type json

### ISSUE THREAD

**Issue by pnija** [samtecspg/articulate#320]
- Did you download a release or pull from Master? Which release?
    -- Working form release - v0.11.2
- What operating system are you running?
   -- Ubuntu 16.04
- Are you running locally or in the cloud?
  -- Running locally
- Which browser are you using?
  -- Chrome : Version 69
---------------------------------------------------
Setup the articulate in local successfully. So when i try to  enable a webhook definition in an intent it not working and returning "internal server error". 

SyntaxError: Uncaught error: Unexpected token b in JSON at position 16
api_1       |     at JSON.parse (<anonymous>)
api_1       |     at module.exports (/usr/src/app/modules/agent/tools/callWebhook.agent.tool.js:23:195)
api_1       |     at module.exports (/usr/src/app/modules/agent/tools/respondFulfilledIntent.agent.tool.js:28:9)
api_1       |     at module.exports (/usr/src/app/modules/agent/tools/respondIntent.agent.tool.js:137:9)
api_1       |     at Object.module.exports [as respond] (/usr/src/app/modules/agent/tools/respond.agent.tool.js:219:17)
api_1       |     at Async.waterfall (/usr/src/app/modules/agent/controllers/converse.agent.controller.js:101:24)
api_1       |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5274:14)
api_1       |     at next (/usr/src/app/node_modules/async/dist/async.js:5281:9)
api_1       |     at /usr/src/app/node_modules/async/dist/async.js:906:16
api_1       |     at Async.parallel (/usr/src/app/modules/agent/controllers/converse.agent.controller.js:78:24)

![agent_webhook_error](https://user-images.githubusercontent.com/7920806/45553894-b6e39f80-b852-11e8-90da-83331cc9b979.png)

The error telling that it not a proper json.

---------------------------------------------------------------------------------------------------
In webhook definition my request body json looks like this:
```
{
	"text": "{{text}}",
	"intent": "{{JSONstringify intent}}",
	"slots": "{{JSONstringify slots}}"
}

```
Request Body Type: JSON

it does'nt trigger the error when  Body Type set to None. Our Back end is python. But When using None as body type webhook triggered the POST http request but the request body is empty. I did't get any values in request body. What was the issue? is it with the above json?.

**Comment by wrathagom** [comment]
When you use JSONstringiy you need to use triple curly brackets so that handlebars doesn't escape them and you don't want them to be strings, but rather objects so no quotes.

Your web hook definition should look like:
```
{
    "text": "{{text}}",
    "intent": {{{JSONstringify intent}}},
    "slots": {{{JSONstringify slots}}}
}
```

Please see this article for more information. https://blog.spg.ai/a-bot-with-a-handlebar-mustache-6b2e74edc241

and let me know if that still doesn't get it working.

**Comment by pnija** [comment]
Actually first i did't change the json format it was like 
```
{
    "text": "{{text}}",
    "intent": {{{JSONstringify intent}}},
    "slots": {{{JSONstringify slots}}}
}
```

![error](https://user-images.githubusercontent.com/7920806/45583305-fa82eb80-b8dc-11e8-8aab-fff01f818806.png)


So that time also i got the same error. then i changed json to format double brackets.

**Comment by wrathagom** [comment]
Okay, that looks like a separate error, but let me test to make sure I know what is working on my side.

**Comment by wrathagom** [comment]
I can confirm that the below is what you need in order to create a valid JSON POSt body.

```
{
	"text": "{{text}}",
	"intent": {{{JSONstringify intent}}},
	"slots": {{{JSONstringify slots}}}
}
```

That being said, which API are you trying to connect to? It seems very odd to me that you would POST our default body to a dialog flow API. For some examples of connecting Articulate with APIs you can checkout the Bot Basics tutorial: https://blog.spg.ai/bot-basics-with-articulate-e5fe975cee88

If you continue to have trouble it may be helpful for you to provide any errors that are appearing in the console.

**Comment by avinash-ts** [comment]
me too encountered this exact problem and below is the error from console. Am trying to connect with our local application (my local application webservice works fine when called from a postman client).

rasa_1      | 2018-09-15 12:44:30+0000 [-] "172.18.0.2" - - [15/Sep/2018:12:44:30 +0000] "POST /parse HTTP/1.1" 200 436 "-" "-"
api_1       | Debug: internal, implementation, error
api_1       |     SyntaxError: Uncaught error: Unexpected token } in JSON at position 908
api_1       |     at JSON.parse (<anonymous>)
api_1       |     at module.exports (/usr/src/app/modules/agent/tools/callWebhook.agent.tool.js:23:195)
api_1       |     at module.exports (/usr/src/app/modules/agent/tools/respondFulfilledIntent.agent.tool.js:28:9)
api_1       |     at module.exports (/usr/src/app/modules/agent/tools/respondIntent.agent.tool.js:137:9)
api_1       |     at Object.module.exports [as respond] (/usr/src/app/modules/agent/tools/respond.agent.tool.js:219:17)
api_1       |     at Async.waterfall (/usr/src/app/modules/agent/controllers/converse.agent.controller.js:101:24)
api_1       |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5274:14)
api_1       |     at next (/usr/src/app/node_modules/async/dist/async.js:5281:9)
api_1       |     at /usr/src/app/node_modules/async/dist/async.js:906:16
api_1       |     at Async.parallel (/usr/src/app/modules/agent/controllers/converse.agent.controller.js:78:24)

**Comment by wrathagom** [comment]
@avinash-ts what does you payload look like?

**Comment by avinash-ts** [comment]
Below is content visible at articulate console for intent, and could not notice anything useful on browser console due to 500 error.
{
	"text": "{{text}}",
	"intent": {{{JSONstringify intent}}},
	"slots": {{{JSONstringify slots}}}
}

**Comment by wrathagom** [comment]
The most useful info would be on the terminal/command console not the browser console. Or in the docker logs.

**Comment by wrathagom** [comment]
Does your intent have slots?

**Comment by avinash-ts** [comment]
This intent does not have any slots yet

**Comment by avinash-ts** [comment]
The original error that i posted is from docker.

**Comment by avinash-ts** [comment]
you are right..
Now it has reached out to my local app. However i got an error at application end 
Caused by: org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token.

 I have built a REST service to receive an POJO with two fields text and intent and got this error. If you can recommend on the object type that i should use will be helpful.

I have few other questions. I am trying set up a browser based chatbot on our enterprise application and trying to pilot articulate now to make a case to our executives, but have following questions.

1. Articulate claims this is a pre release only, when shall we have a prod ready version?
2.  Since we are planning to build browser based chatbot, please share any docs or information on the articulate web service (installed on our premise) that chatbot should call for each user input.

**Comment by wrathagom** [comment]
@avinash-ts I honestly have no idea how to do things on the java app side. It may be struggling since intent is itself another object? @malave @ewoo anything you can add there?

As for your questions:

1. We have no planned release schedule. We have pre-release enhancements that will take us out through the end of this year at least. Though I won't promise that we will move from pre-release to full release at that time. That being said we do use Semantic versioning and have releases that are frozen. So if you find a version of Articulate that works for you you can continue to expect support for it, though no feature enhancements.
2. The best place to get the API documentation is once you have Articulate running. You can visit http://localhost:7500/documentation (this assumes it is running locally) but in general interaction should be done with the `/agent/{agentId}/converse` endpoint.

**Comment by avinash-ts** [comment]
@wrathagom OK i got that, please let me know from where myapp should get the sessionid and agentid before placing request to the service http://localhost:7500/agent/ everytime user sends in text.

**Comment by wrathagom** [comment]
The agent id can be found by looking at the `/agent` endpoint. If you only have one agent then it is likely to be 1.

The sessionID can be any string. So long as the same string is supplied the user will be connected with the same conversation/context. So for example if your bot was communicating over SMS, likely you may want the sessionID to be the phone number and maybe some date hash.

**Comment by avinash-ts** [comment]
OK thank you @wrathagom , let me get this started with Poc and reach out to you if i have any further clarifications.

**Comment by wrathagom** [comment]
Okay, @pnija are you still have trouble as well?

**Comment by pnija** [comment]
No after removing slots in the request body it worked successfully! Thanks @wrathagom

**Comment by avinash-ts** [comment]
@wrathagom I have a challenge related to building a dialogue or stories, how would you recommend doing this with Articulate? considering the pizza order example, if i wish to up-sell (would you like to order a drink) or ask more options related to toppings (full, 50:50 etc) how would that work here?
