### ISSUE TITLE
Using PUT on /context/{sessionId}/{id} to empty an intent's slots can corrupt the context object and kill your agent

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#340]
### Issue
To empty a slot, I am using `PUT /context/{sessionId}/{id}` and passing in `{ "slots": { } }` as suggested by the swagger docs Example Value shown. However this will cause the context object to become corrupt and therefore will take down the agent.

The proper way to use the `PUT` method would be to pass-in valid slot names along with explicit empty strings to avoid corrupting the context object.

```
PUT
{
  "slots": {
     "period": "",
    "companyname": ""
  }
}
```

- Please update the swagger docs to correctly show example model.
- Please add validation to ensure properties are rehydrated correctly if none is passed--or at least prevent an update and provide guidance via error message.

**Comment by ewoo** [comment]
**Workaround**
Note that you can correct the corrupted context object simply by calling the above `PUT` method again--passing in the well-formed JSON document as shown above.

**Comment by wrathagom** [comment]
The PUT for context fails because we're flattening the JSON before inserting into Redis and flattening empty objects isn't handled by the library we are using. I think this will be addressed long term by the work @malave is doing, which should eliminate the flattening.

short term though, I've added validation, which requires the slots object to have at least one key when it is present. If it doesn't it throws a validation error

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "child \"slots\" fails because [\"slots\" must have at least 1 children]",
  "validation": {
    "source": "payload",
    "keys": [
      "slots"
    ]
  }
}
```

Addressed by https://github.com/samtecspg/articulate/commit/e1a7c3275113fe5db3498297f83559fad04c429d
