### ISSUE TITLE
the review page isn't showing multi-actions properly

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#520]
![image](https://user-images.githubusercontent.com/1779894/51912706-ed096200-23a2-11e9-96c3-8a6a8edf5e71.png)

They should be split out like they are on the sayings page.

**Comment by wrathagom** [comment]
Use this agent https://gist.github.com/wrathagom/63f0d64698b0bfe174796a23debd49b5

and try to say `boo`

**Comment by malave** [comment]
Ref: https://github.com/samtecspg/articulate/commit/7cef5f13bae9a66cbe1e8f2fbc4a34e5be41daf4 and https://github.com/samtecspg/articulate/commit/baffe8904495cfef430aa86b0170a7171967cbe9

@wrathagom, @dcalvom and @ewoo : 

Changed the pipeline symbol from `+` to `+__+` since this last one is less likely to be used in a name, but in any case I added the validation to the API.

This can be updated by changing the value on this files:

- `local-storage/rasa/rasa-config-tf.yml`
- `api/util/constants.js`
- `api/util/default-settings.json`
- `ui/app/utils/constants.js`

**Comment by malave** [comment]
Also you will need to remove the data from ES, REDIS and RASA and retrain your agent
