### ISSUE TITLE
Category is not available as top level CSO object

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#568]
When we used a category recognizer category used to be a top-level CSO key. Now we default to a single model and the model recognizer chooses between modifiers and default. I believe this means that the top level CSO category will very rarely be filled.

I think we should modify this top level key:
- I the category is recognized it gets assigned here
- If no category is recognized then this key becomes an object of all the categories.

So in the two examples above accessing parameters looks like:

- `{{category.parameters.blah}}`
- `{{category.[Small Talk].parameters.blah}}`

**Comment by dcalvom** [comment]
This one represent a huge change in the structure if you want to use the `category` keyword for all the categories. The `category` keyword in the CSO is already in use to identify the `category` of the current action. I recommend another keyword because `categories` is also in use to load all the categories of the agent.

**Comment by wrathagom** [comment]
How about modifying `conversationStateObject.agent.categories` to store them as an object rather than array? That would enable accessing them like `{{agent.categories.smallTalk.parameters.blah}}`

**Comment by dcalvom** [comment]
This is goint to be the final syntax:

{{categories.smallTalk.parameters.blah}}

Closed by https://github.com/samtecspg/articulate/commit/d51349291d5ab9d584d99918ff31636d7a68ac2a
