### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by harunkelesoglu** [samtecspg/articulate#577]
### Cannot read property 'id' of undefined
i get follow error when click to copy section

` .   Cannot read property 'id' of undefined`

<img width="1400" alt="ekran resmi 2019-02-19 00 32 07" src="https://user-images.githubusercontent.com/9349762/52977380-146db080-33de-11e9-8de1-17d0fd609c2d.png">

**Comment by wrathagom** [comment]
@malave @dcalvom the intended functionality in this case is that we copy the text of the saying into the saying input for the user to label the correct category.

**Comment by wrathagom** [comment]
related to #522

**Comment by dcalvom** [comment]
The issue here is that the `default` model is a logical model. It actually doesn't exist unless you have explicitly created it. I added a combo box for you to select the new category in the review screen so you can copy sayings with categories, also I added the feature to update the category of a saying in case you want to change it.

All of this is on master right now, please wait for the next release.

Closed by https://github.com/samtecspg/articulate/commit/5702e85679ae8f95b1865d56ef2a888af28cda0a

**Comment by mordebip** [comment]
This problem still exist when following the scenario on https://github.com/samtecspg/articulate/issues/864 and trying to copy an answer intended to fill a slot (so not really leading to an action but only completing one)
