### ISSUE TITLE
slot filling

### ISSUE THREAD

**Issue by eluru-rajesh-hubino** [samtecspg/articulate#824]
Hi 
I am using user_name as slot . when user give the input as "my name is david " , then bot should respond as "hey david , how can i help you " . for this i have added {{slots.user_name.value}} but its not working ....
can you please help me .

**Comment by wrathagom** [comment]
Saying it's not working doesn't give us enough information to help you troubleshoot. Can we get a screenshot of what the conversation does do? What your training data looks like, etc? If possible share the entire export with us. Also, please fill out the issue template so that we know which version you are running to eliminate bugs we have squashed in previous versions.

My guess (with little information to go on) is that `David` is not being recognized as a keyword. if it isn't recognized as a keyword it won't fill the slot, which means the handlebars won't work.

**Comment by dcalvom** [comment]
Question answered
