### ISSUE TITLE
[Question] Can articulate use a GPU

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#919]
I have a question about hardware performance optimisations.

Can Articulate benefit from using a GPU.
Probably not, as Rasa is using the non GPU branch of tensorflow.

But if presumably, we switch the GPU branch, what would be the real benefit ?
Will it only increase the perfs of the training, or does the answers also benefit from it ?

**Comment by wrathagom** [comment]
A GPU would likely have negligible impact because only the Tensorflow pieces could take advantage of it (with some work). We still have some spaCy in the mix which I think is actually the slowest piece.

If you need to improve performance then for the moment your best bet is to put Rasa behind a reverse proxy and run multiple instances. We've been playing with this for some time and may build in a round robin functionality eventually.

**Comment by mordebip** [comment]
Thank you, i was wondering, as i'm still learning how does that part work.
