### ISSUE TITLE
Webhook call

### ISSUE THREAD

**Issue by pankajkmr739** [samtecspg/articulate#996]
### Issues
> *How to connect web api.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
articulate-v0.31.1
- What operating system are you running?
Windows 10 Pro
- Are you running locally or in the cloud?
locally
- Which browser are you using?
Chrome
----

### Feature Request

How do take response from api?
I think Articulate UI supports only local APIs.

Please see the snapshot of UI
![image](https://user-images.githubusercontent.com/11496991/76933863-1de48780-6914-11ea-8768-ff2d6f6eb0e0.png)

**Comment by dcalvom** [comment]
That's definitely a bad wording. To get the data from the webhook you can access it through handlebars in the response definition in the actions page.

So if you defined that your webhook is called getUserData and you want the name of that user you access it like this in an action response:

Hi {{webhoooks.getUserData.response.name}}, how are you?

If you are still not sure about this, you can click in the source link below agents response in the conversation bar and explore through the webhook tab in order to know what is the proper route to get your webhook data.
